#!/usr/bin/env python3
import json

r = json.load(open('step3_sanity_report.json'))

print("=" * 70)
print("STEP 3 SANITY CHECK REPORT - SUMMARY")
print("=" * 70)
print()
print(f"Status: {r['summary']['status']}")
print(f"Errors: {r['summary']['errors']}")
print(f"Warnings: {r['summary']['warnings']}")
print()
print(f"Records: {r['checks']['records']['total']} total")
print(f"  - Successful: {r['checks']['records']['ok']}")
print(f"  - Failed: {r['checks']['records']['failed']}")
print(f"  - With warnings: {len(r['checks']['records']['warned_images'])}")
print()
print("Feature Extraction Results:")
print(f"  Geometry: {r['checks']['stepd_report']['geometry_saved']}/{r['checks']['stepd_report']['unique_images']} ({r['checks']['stepd_report']['geometry_saved']/r['checks']['stepd_report']['unique_images']*100:.1f}%)")
print(f"  CLIP: {r['checks']['stepd_report']['clip_saved']}/{r['checks']['stepd_report']['unique_images']} ({r['checks']['stepd_report']['clip_saved']/r['checks']['stepd_report']['unique_images']*100:.1f}%)")
print(f"  Identity: {r['checks']['stepd_report']['identity_saved']}/{r['checks']['stepd_report']['unique_images']} ({r['checks']['stepd_report']['identity_saved']/r['checks']['stepd_report']['unique_images']*100:.1f}%)")
print()
print("Failures Breakdown:")
for k, v in r['checks']['stepd_report']['failures'].items():
    print(f"  {k}: {v}")
print()
print("Key Consistency:")
print(f"  Record keys: {r['checks']['key_consistency']['record_keys']}")
print(f"  Geometry keys: {r['checks']['key_consistency']['geom_keys']} (missing: {r['checks']['key_consistency']['missing_geom_count']})")
print(f"  CLIP keys: {r['checks']['key_consistency']['clip_keys']} (missing: 0)")
print(f"  Identity keys: {r['checks']['key_consistency']['id_keys']} (missing: {r['checks']['key_consistency']['missing_id_count']})")
print()
print("Data Quality:")
print(f"  Geometry: Shape {r['checks']['data_quality']['geometry']['shape']}, No NaN/Inf: {not r['checks']['data_quality']['geometry']['has_nan'] and not r['checks']['data_quality']['geometry']['has_inf']}")
print(f"  CLIP: Shape {r['checks']['data_quality']['clip']['shape']}, Normalized: {r['checks']['data_quality']['clip']['norm_range'][0]:.4f}-{r['checks']['data_quality']['clip']['norm_range'][1]:.4f}")
print(f"  Identity: Shape {r['checks']['data_quality']['identity']['shape']}, Normalized: {r['checks']['data_quality']['identity']['norm_range'][0]:.4f}-{r['checks']['data_quality']['identity']['norm_range'][1]:.4f}")
print()
print("=" * 70)
print("✓ All checks passed! Data is clean and ready for analysis.")
print("=" * 70)

